=== NREL-Distribution-Suites/gdm-standard-input-action/schema/catalog_system.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "description": "Name of the item."
      },
      "description": {
        "type": "string",
        "description": "A brief description of the item."
      },
      "contributor": {
        "type": "string",
        "description": "Name or identifier of the contributor."
      },
      "contributed_date": {
        "type": "string",
        "format": "date",
        "description": "Date when the item was contributed, in YYYY-MM-DD format."
      }
    },
    "required": [
      "name",
      "description",
      "contributor",
      "contributed_date"
    ],
    "additionalProperties": false
  }

=== NREL-Distribution-Suites/gdm-standard-input-action/catalogs/doc.json
{
    "name": "gdm_catalog",
    "description": "Equipment catalog for DistributionSystem models contains over 25000 models for BareConductorEquipment, CapacitorEquipment, ConcentricCableEquipment, DistributionTransformerEquipment, InverterEquipment and SolarEquipment",
    "contributor": "Aadil Latif",
    "contributed_date": "2024-12-04"
}
